name: Build for Linux Architectures

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64, 386]  # List of architectures to build for
    env:
      GOOS: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust to your Go version

      - name: Initialize Go Modules
        run: |
          go mod init github.com/yourusername/elasticsearch-inserter
          go mod tidy  # This will ensure dependencies are downloaded and go.sum is created

      - name: Build for ${{ matrix.goarch }}
        run: |
          CGO_ENABLED=0 GOOS=$GOOS GOARCH=${{ matrix.goarch }} go build -o bin/elasticsearch-inserter-${{ matrix.goarch }} main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esdata-${{ matrix.goarch }}
          path: bin/esdata-${{ matrix.goarch }}
