name: Build for Linux Architectures

on:
  push:
    branches:
      - "main"
  workflow_dispatch:   # Allows manual trigger from the GitHub UI


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64, 386]  # List of architectures to build for
    env:
      GOOS: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust to your Go version

      - name: Initialize Go Modules
        run: |
          go mod init github.com/yourusername/esdata
          go mod tidy  # This will ensure dependencies are downloaded and go.sum is created

      - name: Build for ${{ matrix.goarch }}
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=$GOOS GOARCH=${{ matrix.goarch }} go build -o bin/esdata-${{ matrix.goarch }} main.go

      # This step is added after all builds are done
      - name: Upload all build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: esdata-all-architectures
          path: bin/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "latest"
          files: |
            bin/esdata-amd64
            bin/esdata-arm64
            bin/esdata-386
